org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21
minecraft_version_range=[1.21-beta,1.22)
neo_version=21.0.47-beta
neo_version_range=[21,)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21
mod_id=beams
mod_name=Beams
mod_license=GPLv3
mod_version=1.21-1.14.5
mod_group_id=io.github.davidqf555.minecraft.beams
mod_authors=DavidQF555