modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/DavidQF555/Beams/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
updateJSONURL = "https://raw.githubusercontent.com/DavidQF555/Beams/update/update.json"
displayName = "${mod_name}"
displayURL = "https://github.com/DavidQF555/Beams"
logoFile = "logo.png"
authors = "${mod_authors}"
description = "This mod adds various beams"
[[dependencies.${ mod_id }]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
