modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPLv3"
[[mods]]
modId = "beams"
version = "${file.jarVersion}"
updateJSONURL = "https://raw.githubusercontent.com/DavidQF555/Beams/update/update.json"
displayName = "Beams"
logoFile = "logo.png"
authors = "DavidQF555"
description = 'This mod adds various beams'
[[dependencies.beams]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.beams]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"
