modLoader = "javafml"
loaderVersion = "[44,)"
license = "GPLv3"
[[mods]]
modId = "beams"
version = "${file.jarVersion}"
displayName = "Beams"
logoFile = "logo.png"
authors = "DavidQF555"
description = 'This mod adds various beams'
[[dependencies.beams]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.beams]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
